### Create B2B client
POST http://localhost:5000/api/b2b/clients
Content-Type: application/json
Accept: application/json

{
    "company_name": "Test Electronics ApS"
}

### B2B order
POST http://localhost:5000/api/b2b/orders
X-API-Key: EAETubHHSRXYYwejPGZPYYgMAodeFngFtb-vF9axx6Y
X-API-Secret: vAmYvKISehtV66JXfZYWTkJS4TwcdH_y6OCDzN96KMLHOntSkY-KHkcMyespciR2
Content-Type: application/json
Accept: application/json

{
    "items": [
        {
            "article_id": 1,
            "quantity": 10
        }
    ]
}

### B2B order - multiple articles
POST http://localhost:5000/api/b2b/orders
X-API-Key: EAETubHHSRXYYwejPGZPYYgMAodeFngFtb-vF9axx6Y
X-API-Secret: vAmYvKISehtV66JXfZYWTkJS4TwcdH_y6OCDzN96KMLHOntSkY-KHkcMyespciR2
Content-Type: application/json
Accept: application/json

{
    "items": [
        {
            "article_id": 1,
            "quantity": 10
        },
        {
            "article_id": 2,
            "quantity": 5
        }
    ]
}

### B2B order - invalid credentials
POST http://localhost:5000/api/b2b/orders
X-API-Key: invalid-key
X-API-Secret: invalid-secret
Content-Type: application/json
Accept: application/json

{
    "items": [
        {
            "article_id": 1,
            "quantity": 1
        }
    ]
}