### Create normal user order
POST http://localhost:5000/api/orders
Content-Type: application/json
Accept: application/json

{
    "items": [
        {
            "article_id": 1,
            "quantity": 2
        }
    ]
}


### Create order with multiple products
POST http://localhost:5000/api/orders
Cookie: access_token_cookie={{accessToken}}; csrf_access_token={{csrfToken}};
X-CSRF-TOKEN: {{csrfToken}}
Content-Type: application/json
Accept: application/json

{
    "items": [
        {
            "article_id": 1,
            "quantity": 2
        },
        {
            "article_id": 2,
            "quantity": 1
        }
    ]
}


### Get all orders for current user
GET http://localhost:5000/api/orders
Cookie: access_token_cookie={{accessToken}}; csrf_access_token={{csrfToken}};
X-CSRF-TOKEN: {{csrfToken}}
Accept: application/json


### Get specific order
Cookie: access_token_cookie={{accessToken}}; csrf_access_token={{csrfToken}};
X-CSRF-TOKEN: {{csrfToken}}
GET http://localhost:5000/api/orders/3
Accept: application/json