@accessToken = "something"
@csrfToken = "something"

### Get all products
GET http://localhost:5000/api/products
Cookie: access_token_cookie={{accessToken}}; csrf_access_token={{csrfToken}};
X-CSRF-TOKEN: {{csrfToken}}


### Get product by ID
GET http://localhost:5000/api/products/3
Cookie: access_token_cookie={{accessToken}}; csrf_access_token={{csrfToken}};
X-CSRF-TOKEN: {{csrfToken}}